spring:
  profiles:
    active:
    - dev
---
server:
  port: 8002
  
spring:
  profiles: dev     #开发环境
  application:                    # 这个名字很重要（对外暴露的微服务,在Eureka会用到）
    name: microserivcecloud-dept  #众多不能改
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.152.80:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5          # 数据库维持连接的最小连接诶书
      initial-size: 5      # 初始连接数
      max-total: 5         # 最大来呢技术
      max-wait-millis: 200 # 超时等待时间

eureka:
  client: #客户端注册经Eureka服务类表
    service-url:
     # defaultZone: http://localhost:7001/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: microservicecloud-dept8002 #修改那个又臭又长的名字
    prefer-ip-address: true   #访问路径可显示IP地址
  
---
server:
  port: 8002
  
spring:
  profiles: test   #测试环境
  application:                    # 这个名字很重要（对外暴露的微服务,在Eureka会用到）
    name: microserivcecloud-dept  #众多不能改
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.152.80:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5          # 数据库维持连接的最小连接诶书
      initial-size: 5      # 初始连接数
      max-total: 5         # 最大来呢技术
      max-wait-millis: 200 # 超时等待时间

eureka:
  client: #客户端注册经Eureka服务类表
    service-url:
     # defaultZone: http://localhost:7001/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: microservicecloud-dept8002 #修改那个又臭又长的名字
    prefer-ip-address: true   #访问路径可显示IP地址

# 请保存位UTF-8格式